apiVersion: v1
kind: Service
metadata:
  name: bench
  namespace: bench
  labels:
    app.kubernetes.io/part-of: arca-suite
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bench
  ports:
    - name: http
      port: 80
      targetPort: 8092
